apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "digit-mcp.fullname" . }}
  labels:
    {{- include "digit-mcp.labels" . | nindent 4 }}
data:
  MCP_TRANSPORT: {{ .Values.env.MCP_TRANSPORT | quote }}
  MCP_PORT: {{ .Values.env.MCP_PORT | quote }}
  CRS_ENVIRONMENT: {{ .Values.env.CRS_ENVIRONMENT | quote }}
  CRS_TENANT_ID: {{ .Values.env.CRS_TENANT_ID | quote }}
