apiVersion: v1
kind: Secret
metadata:
  name: {{ include "digit-mcp.fullname" . }}
  labels:
    {{- include "digit-mcp.labels" . | nindent 4 }}
type: Opaque
data:
  CRS_USERNAME: {{ .Values.secret.CRS_USERNAME | b64enc | quote }}
  CRS_PASSWORD: {{ .Values.secret.CRS_PASSWORD | b64enc | quote }}
